version: "3.8"

services:
  elementary_school_api:
    image: elementary_school_api:1.0
    container_name: elementary_school_api
    build: ../
    ports:
      - ${ELEMENTARY_SCHOOL_API_PORT}:3000
    environment:
      - JWT_SECRET=/run/secrets/jwt_secret
      - MONGO_DATABASE_CONTAINER_NAME=${MONGO_CONTAINER_NAME}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - MONGO_DATABASE_PASSWORD=/run/secrets/mongo_database_password
      - MONGO_DATABASE_USERNAME=/run/secrets/mongo_database_username
      - PEPPER=/run/secrets/pepper
      - RSA_PRIVATE_KEY=/run/secrets/rsa_private_key
    networks:
      - elementary-school-database
      - elementary-school-frontend
    volumes:
      - ../:/app
    secrets:
      - jwt_secret
      - mongo_database_password
      - mongo_database_username
      - pepper
      - rsa_private_key
  
  elementary_school_mongo_db:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - ${MONGO_DATABASE_PORT}:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_database_password
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_database_username
    networks:
      - elementary-school-database
    volumes:
      - ${MONGO_DATABASE_SETUP_FILE_LOCATION}:/docker-entrypoint-initdb.d/database_setup.js
    secrets:
      - mongo_database_password
      - mongo_database_username

  elementary_school-mongo-express:
    image: mongo-express
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME}
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_BASICAUTH_PASSWORD_FILE=/run/secrets/mongo_express_web_password
      - ME_CONFIG_BASICAUTH_USERNAME_FILE=/run/secrets/mongo_express_web_username
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/mongo_database_password
      - ME_CONFIG_MONGODB_ADMINUSERNAME_FILE=/run/secrets/mongo_database_username
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DATABASE_CONTAINER_NAME}
    networks:
      - elementary-school-database
    secrets:
      - mongo_database_password
      - mongo_database_username
      - mongo_express_web_password
      - mongo_express_web_username

secrets:
  jwt_secret:
    file: ./secrets/security/jwt_secret.txt
  mongo_database_password:
    file: ./secrets/database/mongo_database_password.txt
  mongo_database_username:
    file: ./secrets/database/mongo_database_username.txt
  mongo_express_web_password:
    file: ./secrets/database/mongo_express_web_password.txt
  mongo_express_web_username:
    file: ./secrets/database/mongo_express_web_username.txt
  pepper:
    file: ./secrets/security/pepper.txt
  rsa_private_key:
    file: ./secrets/security/rsa_private_key.pem

networks:
  elementary-school-database:
  elementary-school-frontend: